print("Hello world from Lua!")

RegisterHook("/Script/Engine.PlayerController:ClientRestart", function(Context)
  RegisterHook("/Script/Pal.PalCharacterParameterComponent:SetHP", function()
    print("SetHP fired")
  end)
  RegisterHook("/Script/Pal.PalUtility:SetHPByRateToCharacter", function()
    print("SetHPByRateToCharacter fired")
  end)
  RegisterHook("/Script/Pal.PalUtility:SetHPByRateToHandle", function()
    print("SetHPByRateToHandle fired")
  end)
  RegisterHook("/Script/Pal.PalStaticConsumeItemData:GetRestoreHP", function()
    print("GetRestoreHP fired")
  end)
end)
