---@meta

---@class UWBP_IngameMenu_Chest_Filter_C : UUserWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field Overlay_Desc UOverlay
---@field Text_GuildMenberHead UBP_PalTextBlock_C
---@field WBP_CommonButton_CheckAll UWBP_CommonButton_1_C
---@field WBP_CommonButton_Confirm UWBP_CommonButton_1_C
---@field WBP_CommonButton_UncheckAll UWBP_CommonButton_1_C
---@field WBP_IngameMenu_Chest_FilterContent UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_1 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_2 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_3 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_4 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_5 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_6 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_7 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_8 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_9 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_10 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_11 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_IngameMenu_Chest_FilterContent_12 UWBP_IngameMenu_Chest_FilterContent_C
---@field WBP_Menu_btn UWBP_Menu_btn_C
---@field WBP_PalCommonWindow UWBP_PalCommonWindow_C
---@field WrapBox_FilterList UWrapBox
---@field OnClickedCloseButton FWBP_IngameMenu_Chest_Filter_COnClickedCloseButton
---@field OnClickedAllCheckButton FWBP_IngameMenu_Chest_Filter_COnClickedAllCheckButton
---@field OnClickedAllUncheckButton FWBP_IngameMenu_Chest_Filter_COnClickedAllUncheckButton
---@field OnClickedApplyButton FWBP_IngameMenu_Chest_Filter_COnClickedApplyButton
UWBP_IngameMenu_Chest_Filter_C = {}

function UWBP_IngameMenu_Chest_Filter_C:FocusToConfirmButton() end
---@param Checked boolean
function UWBP_IngameMenu_Chest_Filter_C:SetAllChecker(Checked) end
function UWBP_IngameMenu_Chest_Filter_C:SetupAsItemFilter() end
---@param FilterId FName
---@param FilterTextId FName
---@return UWBP_IngameMenu_Chest_FilterContent_C
function UWBP_IngameMenu_Chest_Filter_C:AddContentItem(FilterId, FilterTextId) end
function UWBP_IngameMenu_Chest_Filter_C:ClearContent() end
---@param NewParam UWidget
function UWBP_IngameMenu_Chest_Filter_C:GetDesiredFocusTarget(NewParam) end
function UWBP_IngameMenu_Chest_Filter_C:BndEvt__WBP_IngameMenu_Chest_Filter_WBP_Menu_btn_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature() end
function UWBP_IngameMenu_Chest_Filter_C:BndEvt__WBP_IngameMenu_Chest_Filter_WBP_CommonButton_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature() end
function UWBP_IngameMenu_Chest_Filter_C:BndEvt__WBP_IngameMenu_Chest_Filter_WBP_CommonButton_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature() end
function UWBP_IngameMenu_Chest_Filter_C:BndEvt__WBP_IngameMenu_Chest_Filter_WBP_CommonButton_Confirm_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature() end
---@param EntryPoint int32
function UWBP_IngameMenu_Chest_Filter_C:ExecuteUbergraph_WBP_IngameMenu_Chest_Filter(EntryPoint) end
function UWBP_IngameMenu_Chest_Filter_C:OnClickedApplyButton__DelegateSignature() end
function UWBP_IngameMenu_Chest_Filter_C:OnClickedAllUncheckButton__DelegateSignature() end
function UWBP_IngameMenu_Chest_Filter_C:OnClickedAllCheckButton__DelegateSignature() end
function UWBP_IngameMenu_Chest_Filter_C:OnClickedCloseButton__DelegateSignature() end


